openapi: 3.0.0
info:
  title: User Management API
  description: API for user registration and login
  version: 1.0.0

paths:
  /auth/register:
    post:
      summary: Register a new user
      parameters:
        - in: query
          name: username
          required: true
          schema:
            type: string
        - in: query
          name: password
          required: true
          schema:
            type: string
        - in: query
          name: email
          required: true
          schema:
            type: string
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid request data
        '409':
          description: User already exists
      tags:
        - User

  /auth/login:
    post:
      summary: Log in with username and password
      parameters:
        - in: query
          name: username
          required: true
          schema:
            type: string
        - in: query
          name: password
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Unauthorized
        '400':
          description: Invalid request data
      tags:
        - User

components:
  schemas:
    LoginResponse:
      type: object
      properties:
        token:
          type: string
